#!/bin/sh -e

PROGNAME=Xsession
message () {
  MESSAGE="$PROGNAME: $*"
  echo "$MESSAGE" >&2
  # FIXME
  if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
    echo "$MESSAGE" | xmessage -center -file -
  fi
}

errormsg() {
  message "$@"
  exit 1
}

ERRFILE=$HOME/.xsession-errors

if (umask 077 && touch "$ERRFILE") 2> /dev/null && [ -w "$ERRFILE" ] &&
  [ ! -L "$ERRFILE" ]; then
  chmod 600 "$ERRFILE"
else
  errormsg "Unable to create errors file."
fi

exec >>"$ERRFILE" 2>&1

echo "$PROGNAME: X session started for $LOGNAME at $(date)"

set +e
for part in $(run-parts -t /etc/X11/Xsession.d); do
  . $part
done

exit 0
