#!/bin/sh -e

PROGNAME=Xsession
message () {
  MESSAGE="$PROGNAME: $*"
  echo "$MESSAGE" >&2
  # FIXME
  if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
    echo "$MESSAGE" | xmessage -center -file -
  fi
}

errormsg() {
  message "$@"
  exit 1
}

set +e
for part in $(run-parts -t /etc/X11/Xsession.d); do
  . $part
done

exit 0
